server:
  port: 8090
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: news-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    password: Vihaan@2020
    username: root
    url: jdbc:mysql://newsdb-mysql:3306/newsdb
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
#eureka:
#  instance:
#    preferIpAddress: 'true'
#  client:
#    fetchRegistry: 'true'
#    registerWithEureka: 'true'
#    serviceUrl:
#      defaultZone: http://eureka-service:8070/eureka/
jwt:
  signing:
    key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ
springdoc:
  version: 1.6.11
