apiVersion: v1
kind: Service
metadata:
  name: news-service
  labels:
    app: news-service
spec:
  type: ClusterIP
  selector:
    app: news-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
